---
title: "Project proposal 1"
author: "Amy Kouch"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 01. Electric vehicle population in Washington
The electric vehicle market is expected to grow substantially in the upcoming decade. I am someone who is very excited for this transition and have done previous research into new models that will come out.

### Overview
This challenge seeks to better understand the electric vehicle population in the state of Washington. What types of electric vehicle models are being bought? Who is buying them? What is their mile range?

### Data

The dataset would be used courtesy of [data.wa.gov's Battery Electric Vehicles (BEVs) and Plug-in Hybrid Electric Vehicles (PHEVs)](https://catalog.data.gov/dataset/electric-vehicle-population-data). This dataset includes electric vehicles registered through Washington State Department of Licensing (DOL). If possible, I would see if there are datasets for other states as well.

### Goals
1) Create a map of vehicle locations throughout Washington, to identify what regions people are buying electric vehicles
2) Understand the most popular models and their qualities (mileage, year)
3) Compare battery electric vehicles to plug-ins

## 02. Electricity emissions
One of the most harmful aspects of energy generation are the emissions of air pollutants associated. Because some air pollutants have different health impacts, it is important to quantify these emissions.

### Overview
Compare emissions from different sources of generation

### Data
Obtain data from the [US Energy Information Administration](https://www.eia.gov/electricity/data.php#elecenv) about the emissions generated by plant and by region. We would most likely need to combine different datasets. Ones I'm particularly interested in currently are the generation, capacity, sales, consumption, and costs dataset.

### Goals
1) Compare different types of fossil fuel generation to nuclear and renewable generation's emissions
2) Determine the cost of generation across different plants and compare this to a "cost" of pollutants on human health (must be researched)
3) Create a map of the areas most affected by the different air pollutants (NOX, SO2, CO2)

## 03. Mapping how the United States generates its electricity

Recreating [these analyses](https://www.washingtonpost.com/graphics/national/power-plants/?noredirect=on&utm_term=.9577c0f5f539) from data obtained. 

### Overview
As a student in the Civil & Environmental Engineering department's Atmosphere/Energy program, I am fascinated by how the United States generates its electricity and how this changes over time. 

### Data
As cited from the article, data obtained from [Energy Information Administration's “Operable electric generating plants in the United States by energy source”](https://www.eia.gov/maps/map_data/PowerPlants_US_EIA.zip) and a more detailed monthly report from the [Annual Electric Generator Report, EIA-860M, Monthly Update to the Annual Electric Generator Report and EIA-923, Power Plant Operations Report](http://www.eia.gov/electricity/monthly/)

### Goals

1) From the data, be able to visualize the portions of the US electricity that is generated by different resources and how that has changed from 2001 to 2016. 
2) Visualize the states with the highest portion of natural gas, coal, nuclear, hydro, wind, solar, oil and other resources to produce electricity
3) Map the geographic locations of different power plants and energy producers (natural gas, coal, nuclear, hydro, wind, solar, oil) on a map of the United States
4) Go beyond the analysis and separate the US into its grid regions and demonstrate the % of electricity that makes up each grid. 
5) Conduct similar analyses to ["How does your state make energy?" NY Times Article](How Does Your State Make Electricity?)
