---
title: "Project proposal 2"
author: "Amy Kouch"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mapping how the United States generates its electricity

Recreating [these analyses](https://www.washingtonpost.com/graphics/national/power-plants/?noredirect=on&utm_term=.9577c0f5f539) from data obtained for the years 2018 and 2003 (15 years). 

### Overview

As a student in the Civil & Environmental Engineering department's Atmosphere/Energy program, I am fascinated by how the United States generates its electricity and how this has changed over time. My goal with my C01 project is to explore how states differ in their electricity generation and explore steps we need in order to move towards a renewable future. 

### Data

As cited from the article, data obtained from [Energy Information Administration's “Operable electric generating plants in the United States by energy source”](https://www.eia.gov/maps/map_data/PowerPlants_US_EIA.zip) will be used to create geospatial maps. After this week, I hope to have a better understanding of how to open these files to create these visual maps. 

To analyze the electricity generation by power plant, I will obtain more details from [Annual Electric Generator Report](http://www.eia.gov/electricity/monthly/) and  [EIA-860M](https://www.eia.gov/electricity/data/eia860/). I will be combining the Plant and Generator datasets together. 

### Goals

1) Visualize:
* the portions of the US electricity that is generated by different resources 
* trends in the changes in electricity generation by amount and fuel type from 2003 to 2018
* the states with the highest portion of natural gas, coal, nuclear, hydro, wind, solar, oil and other resources to produce electricity
* the geographic locations of different power plants and energy producers (natural gas, coal, nuclear, hydro, wind, solar, oil) on a map of the United States

2) Analyze: 
* the US electricity separated into its grid regions and the % of electricity that makes up each grid
* the cost, quantity, and time it would take to build wind and solar farms to replace all fossil fuel generation sources (by state and by grid region) in the US. 
* based off of current trends over the last 15 years, which states will reach 100% renewable energy first? Create maps forecasting how renewable the US will be in the next 5, 10, 20, 50 and 100 years

### Challenge: 100% Renewable

The purpose of the challenge will be to explore the implications of a 100% renewable nation.

The team will be instructed to perform the following for this challenge:

1) List the states by highest fossil fuel generation to lowest. Do the same for renewable generation.
2) Identify the given cost of building a solar power plant and a wind power plant (outside research required for this)
3) Determine how expensive it would be to transition all fossil fuel resources into renewable energy. How many fossil fuel plants will need to retire in each state? How much electricity needs to be replaced? How many renewable plants will need to be built in each state? 

### Decomposition

Week 3

* Combine the different datasets and clean the datasets into tidydata with the following variables: state, plant, fuel type, electricity generation, longitude, latitude

Week 4 (progress report 1 due)

* Recreate all of the visualizations in the WashingtonPost article including geospatial maps by fuel source and a table of fuel sources by state
* Create visualization of trends from 2003 - 2018 of changing fuel sources in the US

Week 5

* Forecast how renewable the US will be the next 5, 10, 20, 50 and 100 years without changing to current transition rates
* Research costs of power plants and time for construction

Week 6 (progress report 2 due)

* Prepare challenge for the rest of the team by running through the challenge 
* Determine cost and quantity of plants needed to turn 100% renewable

Week 7 (challenge for the rest of the team)

* Help with challenge if needed
* Determine time it would take for each state to turn 100% renewable

Week 8 

* Identify which portions of the project to include in the final report
* Make sure visualizations are presentation-ready
* Rough draft of final report

Week 9 (final report due)

* Final edits to final report
